apiVersion: v1
kind: Service
metadata:
  name: outlaws-frontend
  namespace: cmy-infra-admins
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  selector:
    run: outlaws-frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
